### PR TITLE
Chad Coker Ajax Reddit Slideshow

### PR DESCRIPTION
**Pull request by willylikestokayak**
**Deliverable Submission**

Please describe your comfort and completeness levels before submitting.

Comfort Level (1-5): 1

Completeness Level (1-5): 2

What did you think of this deliverable?: This was very difficult for me; using other code as an example and code, I still struggle with this concept.

### CODE REVIEW

**Comment by jmduhon** [comment]
did you ever get to a point where you could console log the urls from reddit? if you couldn't get the slideshow part of it working that's fine. I just want to make sure you can grab data from APIs

**Comment by willylikestokayak** [comment]
I was getting images prior to trying to add the slide show plug-in.  After
using the slide-show plug-in it broke and I was stuck again.

**Comment by jmduhon** [comment]
K, well that's the part that everyone had trouble with. I'm gonna count this as done. Feel free to give the slideshow part another try using setInterval and jQuery to change the src attribute of an  tag. It would be a good exercise. But as far as I'm concerned this is turned in.

**Comment by willylikestokayak** [comment]
Thanks for the feedback.  One of the main reason I decided to use an API for my blackjack game was because of that assignment and how little I understood of it.

**Pull request closed without merging**
